builders:
  collection_builder:
    import: "package:factory_mapper/src/builder.dart"
    builder_factories: ["factoryBuilder"]
    build_extensions:
      "$lib$": [".g.dart"]
    auto_apply: dependents
    build_to: source
